version: "3.8"

services:
  snake:
    build: .
    container_name: snake_game
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/snake_game:/tmp/.X11-unix
    stdin_open: true
    tty: true