apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - grafana.yaml
  - prometheus.yaml  

namespace: mysnake-app

images:
  - name: alok2026/flask-app
    newTag: v1.1  
