apiVersion: v1
kind: Service
metadata:
  name: snake-game-service
  namespace: snake-game  
spec:
  selector:
    app: snake-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort

